spring:
  application:
    name: online-auction
  datasource:
    url: jdbc:postgresql://localhost:5432/online-auction
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:123}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
