spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: online-auction
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${PORT}

# JWT Configuration
jwt:
  secret: D(c(J^1`S4:S_be}p}'nK==UVO8I~2!/rQmH+U2nl2E7k<jN7#
  access-token-expiration: 3600000 # 1 hour in milliseconds
  refresh-token-expiration: 604800000 # 7 days in milliseconds

# OTP Configuration
otp:
  expiration-minutes: 10

# Cookie Configuration (For refresh token)
cookie:
  secure: false # Set to true in production (requires HTTPS)
  same-site: Lax # Lax for good balance, Strict for maximum security
