spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: online-auction
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  # File Upload Configuration
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 30MB

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Email Configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        transport:
          protocol: smtp

server:
  port: ${PORT}

# JWT Configuration
jwt:
  secret: D(c(J^1`S4:S_be}p}'nK==UVO8I~2!/rQmH+U2nl2E7k<jN7#
  access-token-expiration: 3600000 # 1 hour in milliseconds
  refresh-token-expiration: 604800000 # 7 days in milliseconds

# OTP Configuration
otp:
  expiration-minutes: 10

# Cookie Configuration (For refresh token)
cookie:
  secure: true
  same-site: Strict

# Google reCAPTCHA Configuration
recaptcha:
  secret-key: ${RECAPTCHA_SECRET_KEY}
  site-key: ${RECAPTCHA_SITE_KEY}
  verify-url: https://www.google.com/recaptcha/api/siteverify

# Application Configuration
app:
  name: BidStorm
  url: ${APP_URL}
  default-avatar-url: ${DEFAULT_AVATAR_URL}

# CORS Configuration
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}

# AWS S3 Configuration
aws:
  s3:
    access-key-id: ${AWS_ACCESS_KEY_ID}
    secret-access-key: ${AWS_SECRET_ACCESS_KEY}
    bucket-name: ${AWS_S3_BUCKET_NAME}
    region: ${AWS_S3_REGION}

# Stripe Payment Configuration
stripe:
  api:
    key: ${STRIPE_API_KEY}
  publishable:
    key: ${STRIPE_PUBLISHABLE_KEY}
  webhook:
    secret: ${STRIPE_WEBHOOK_SECRET}
  currency: USD

# Logging Configuration
logging:
  level:
    com.taitrinh.online_auction: DEBUG
    org.springframework.messaging: DEBUG
    org.springframework.web.socket: DEBUG
